Repository slackapi/bolt-js, pull requests merged in 2019-12, with the labels that each got.

#326 adding type as a valid constraint for app actions
  src/App.spec.ts
  src/App.ts
  src/types/actions/index.ts
Labels: enhancement

#339 🧹 mostly low-hanging ts lint fixes, ts lint as part of test
  README.md
  package.json
  src/App.ts
  src/ExpressReceiver.spec.ts
  src/ExpressReceiver.ts
  src/conversation-store.ts
  src/helpers.ts
Labels: semver:patch

#343 Fix #341 - Make channel file in block_actions payload optional (+ add view field)
  src/types/actions/block-action.ts
Labels: TypeScript-specific, enhancement, semver:patch

#344 Fix #342 TypeScript: multi-select/radio button block elements are still unsupported
  src/types/actions/block-action.ts
Labels: TypeScript-specific, bug, enhancement

#349 improved type resolution for action method
  integration-tests/.gitignore
  integration-tests/.vscode/launch.json
  integration-tests/README.md
  integration-tests/package.json
  integration-tests/types/action.ts
  integration-tests/types/index.d.ts
  integration-tests/types/tsconfig.json
  package.json
  src/App.ts
Labels: enhancement
