Repository slackapi/bolt-js, pull requests merged in 2020-02, with the labels that each got.

#369 Convert say, ack, and respond to return promises
  README.md
  docs/_advanced/context.md
  docs/_advanced/ja_context.md
  docs/_basic/acknowledging_requests.md
  docs/_basic/ja_acknowledging_requests.md
  docs/_basic/ja_listening_actions.md
  docs/_basic/ja_listening_messages.md
  docs/_basic/ja_listening_modals.md
  docs/_basic/ja_listening_responding_commands.md
  docs/_basic/ja_listening_responding_options.md
  docs/_basic/ja_opening_modals.md
  docs/_basic/ja_responding_actions.md
  docs/_basic/ja_sending_messages.md
  docs/_basic/ja_updating_pushing_modals.md
  docs/_basic/listening_actions.md
  docs/_basic/listening_messages.md
  docs/_basic/listening_modals.md
  docs/_basic/listening_responding_commands.md
  docs/_basic/listening_responding_options.md
  docs/_basic/opening_modals.md
  docs/_basic/responding_actions.md
  docs/_basic/sending_messages.md
  docs/_basic/updating_pushing_modals.md
  docs/_tutorials/getting_started.md
  docs/_tutorials/ja_getting_started.md
  package.json
  src/App.spec.ts
  src/App.ts
  src/ExpressReceiver.spec.ts
  src/ExpressReceiver.ts
  src/middleware/builtin.spec.ts
  src/test-helpers.ts
  src/types/receiver.ts
  src/types/utilities.ts
  tsconfig.test.json
Labels: enhancement

#359 Fix #168 #354 Add `logger`, `client` to the list of args send through to listeners
  src/App.spec.ts
  src/App.ts
  src/conversation-store.spec.ts
  src/middleware/builtin.spec.ts
  src/middleware/process.ts
  src/types/middleware.ts
Labels: enhancement, semver:minor

#387 Fix #382 Missing invite_requested event type
  src/types/events/base-events.ts
Labels: enhancement

#393 Merge #359 #387 to the @slack/bolt@next branch
  src/App.spec.ts
  src/App.ts
  src/conversation-store.spec.ts
  src/middleware/builtin.spec.ts
  src/middleware/process.ts
  src/types/events/base-events.ts
  src/types/middleware.ts
Labels: enhancement, semver:major

#398 Fix an error on README
  README.md
Labels: docs

#410 Fix #348 app.view() is not described in the README
  README.md
Labels: docs

#408 Add checkboxes action payload
  src/types/actions/block-action.ts
Labels: enhancement, semver:minor

#409 [v2] Add checkboxes action payload
  src/types/actions/block-action.ts
Labels: enhancement

#411 [v2] Specifies view submission response action types (#404)
  src/types/view/index.ts
Labels: enhancement

#399 [v2] Fix an error on README
  README.md
Labels: docs

#406 Fix #405 by providing a better way to configure logger
  src/App.spec.ts
  src/App.ts
Labels: bug, semver:minor

#413 [v2] Fix #405 by providing a better way to configure logger
  src/App.spec.ts
  src/App.ts
Labels: bug
