Repository slackapi/bolt-js, pull requests merged in 2020-10, with the labels that each got.

#656 added support for event api payload changes
  src/types/events/index.ts
Labels: semver:minor, untriaged

#659 Update Maintainer's Guide to include more information on forking + branching
  .github/maintainers_guide.md
Labels: docs

#651 [#220] Add deployment guide for Heroku
  docs/_config.yml
  docs/_deployments/heroku.md
  docs/_includes/sidebar.html
  docs/assets/event-subscriptions-page.png
  docs/assets/interactivity-and-shortcuts-page.png
  examples/getting-started-with-heroku/.gitignore
  examples/getting-started-with-heroku/LICENSE
  examples/getting-started-with-heroku/Procfile
  examples/getting-started-with-heroku/README.md
  examples/getting-started-with-heroku/app.js
  examples/getting-started-with-heroku/package.json
Labels: docs

#665 Fix SVG
  docs/assets/bolt-js-logo.svg
Labels: untriaged

#667 Update template URLs to use main
  .github/issue_template.md
  .github/pull_request_template.md
Labels: docs

#668 Update Getting Started guide to reference Getting Started example app
  docs/_tutorials/getting_started.md
Labels: docs
