Repository slackapi/bolt-js, pull requests merged in 2020-01, with the labels that each got.

#363 Tweak a sentence in Japanese documentation
  docs/_advanced/ja_authorization.md
Labels: docs

#356 Improve code format consistency in docs
  README.md
  docs/_advanced/authorization.md
  docs/_advanced/context.md
  docs/_advanced/error_handling.md
  docs/_advanced/ja_authorization.md
  docs/_advanced/ja_context.md
  docs/_advanced/ja_error_handling.md
  docs/_advanced/ja_middleware_listener.md
  docs/_advanced/ja_receiver.md
  docs/_advanced/middleware_listener.md
  docs/_advanced/receiver.md
  docs/_basic/acknowledging_requests.md
  docs/_basic/ja_acknowledging_requests.md
  docs/_basic/ja_listening_actions.md
  docs/_basic/ja_listening_messages.md
  docs/_basic/ja_listening_responding_commands.md
  docs/_basic/ja_listening_responding_options.md
  docs/_basic/ja_responding_actions.md
  docs/_basic/ja_sending_messages.md
  docs/_basic/listening_actions.md
  docs/_basic/listening_messages.md
  docs/_basic/listening_modals.md
  docs/_basic/listening_responding_commands.md
  docs/_basic/listening_responding_options.md
  docs/_basic/responding_actions.md
  docs/_basic/sending_messages.md
Labels: docs

#357 Add more unit tests for built-in middleware and ExpressReceiver
  package.json
  src/App.spec.ts
  src/ExpressReceiver.spec.ts
  src/ExpressReceiver.ts
  src/conversation-store.spec.ts
  src/middleware/builtin.spec.ts
  src/test-helpers.ts
Labels: tests

#368 updated release steps in maintainers guide
  .github/maintainers_guide.md
Labels: docs

#370 fixed ack in ExpressReceiver firing twice. Issue #327
  src/ExpressReceiver.ts
Labels: bug

#373 Update Bolt Getting Started for Granular Bot Permissions
  docs/.gitignore
  docs/_tutorials/getting_started.md
  docs/_tutorials/ja_getting_started.md
  docs/assets/bot-token.png
Labels: docs

#378 Fix GBP assets in Getting Started guide
  docs/assets/basic-information-page.png
  docs/assets/bot-token.png
Labels: docs

#362 Fix #324 Responding with 401 status, not 500 for signature verification failures
  src/ExpressReceiver.spec.ts
  src/ExpressReceiver.ts
Labels: enhancement, semver:patch

#379 Fix #377 ExpressReceiver's RespondFn implementation doesn't accept a string
  src/ExpressReceiver.spec.ts
  src/ExpressReceiver.ts
Labels: bug
