Repository slackapi/bolt-js, pull requests merged in 2020-11, with the labels that each got.

#681 Update issue template to include example code type
  .github/issue_template.md
Labels: docs

#683 Fix #641 by adding Japanese version of Steps from Apps docs
  docs/_config.yml
  docs/_steps/ja_adding_editing_workflow_step.md
  docs/_steps/ja_creating_workflow_step.md
  docs/_steps/ja_executing_workflow_steps.md
  docs/_steps/ja_saving_workflow_step.md
  docs/_steps/ja_workflow_steps_overview.md
Labels: docs

#676 Fixing this code be compatiable with v2.x I also added some comments …
  examples/hubot-example/script.js
Labels: enhancement

#686 Update README to refer authorizations rather than authed_users
  README.md
Labels: docs

#521 Add org app support to bolt
  package.json
  src/App.spec.ts
  src/App.ts
  src/types/actions/block-action.ts
  src/types/actions/dialog-action.ts
  src/types/actions/interactive-message.ts
  src/types/actions/workflow-step-edit.ts
  src/types/command/index.ts
  src/types/options/index.ts
  src/types/shortcuts/global-shortcut.ts
  src/types/shortcuts/message-shortcut.ts
  src/types/view/index.ts
Labels: draft, enhancement, semver:minor

#662 Track ruby-version for consistent local docs builds with rbenv
  docs/.ruby-version
Labels: discussion, docs

#691 v2.5.0
  package.json
Labels: release
