Repository slackapi/bolt-js, pull requests merged in 2020-05, with the labels that each got.

#479 added oauth package to bolt
  docs/_basic/authenticating_oauth.md
  package.json
  src/App.spec.ts
  src/App.ts
  src/ExpressReceiver.spec.ts
  src/ExpressReceiver.ts
  src/helpers.ts
Labels: enhancement, semver:minor

#503 fixed oauth custom expressReceiver bugs
  docs/_basic/authenticating_oauth.md
  src/App.ts
Labels: bug, semver:patch

#505 Added `calls_rejected` event
  src/types/events/base-events.ts
Labels: enhancement, semver:minor

#499 Add middleware matching app_mention events' text
  src/middleware/builtin.spec.ts
  src/middleware/builtin.ts
Labels: enhancement
