Repository slackapi/bolt-js, pull requests merged in 2021-01, with the labels that each got.

#723 Branch name change from master to main
  .github/contributing.md
Labels: untriaged

#722 bump axios to v0.21.1 to fix vuln (CVE-2020-28168)
  package.json
Labels: security

#709 Improve types for message events and all subtypes
  src/App.ts
  src/helpers.ts
  src/middleware/builtin.spec.ts
  src/middleware/builtin.ts
  src/types/events/base-events.ts
  src/types/events/index.ts
  src/types/events/message-events.ts
  types-tests/message.test-d.ts
Labels: enhancement, semver:minor

#724 Release v2.6.0
  package.json
Labels: release

#730 Fix #726 #729 by checking if enteprise is null
  src/App.spec.ts
  src/App.ts
Labels: bug

#731 v2.6.1
  package.json
Labels: release, semver:patch

#738 Fix check for is_enterprise_install for slash commands
  src/App.spec.ts
  src/App.ts
Labels: untriaged

#734 removed orgAuthorize
  docs/_basic/authenticating_oauth.md
  docs/_basic/ja_authenticating_oauth.md
  docs/_tutorials/reference.md
  src/App.spec.ts
  src/App.ts
Labels: enhancement, semver:major

#728 updated minimum node version to 12.13.0, updated minimum typescript t…
  docs/_tutorials/using-typescript.md
  package.json
Labels: enhancement

#739 Add thread_ts to AppMentionEvent interface
  src/middleware/builtin.spec.ts
  src/types/events/base-events.ts
Labels: enhancement

#740 Add channel to all MessageEvent interfaces
  src/middleware/builtin.spec.ts
  src/types/events/message-events.ts
  types-tests/message.test-d.ts
Labels: enhancement

#630 Adding SocketModeReceiver to Bolt-js
  docs/_basic/socket_mode.md
  examples/socket-mode/README.md
  examples/socket-mode/app.js
  examples/socket-mode/package.json
  package.json
  src/App.ts
  src/ExpressReceiver.ts
  src/SocketModeReceiver.ts
  src/index.ts
Labels: enhancement

#745 added migration guide for v3
  .github/workflows/ci-build.yml
  docs/_tutorials/migration_v3.md
  package.json
Labels: docs

#746 Add Japanese version to #745
  docs/_tutorials/ja_migration_v3.md
  docs/_tutorials/migration_v3.md
Labels: docs

#748 Release v2.7.0
  package.json
Labels: release

#658 Adding support for HTTPS servers, and other listening and TLS options
  src/App.spec.ts
  src/App.ts
  src/ExpressReceiver.spec.ts
  src/ExpressReceiver.ts
  src/errors.ts
Labels: enhancement, semver:minor

#751 Fix Socket Mode documents
  docs/_basic/ja_socket_mode.md
  docs/_basic/socket_mode.md
Labels: docs

#753 Implements HTTPReceiver
  docs/_basic/socket_mode.md
  package.json
  src/App.ts
  src/errors.ts
  src/index.ts
  src/receivers/ExpressReceiver.spec.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/verify-request.ts
  types/tsscmp.d.ts
Labels: untriaged

#744 Bolt for JavaScript version 3
  .github/maintainers_guide.md
  .github/workflows/ci-build.yml
  docs/_basic/authenticating_oauth.md
  docs/_basic/ja_authenticating_oauth.md
  docs/_basic/ja_socket_mode.md
  docs/_basic/socket_mode.md
  docs/_tutorials/ja_migration_v3.md
  docs/_tutorials/ja_using-typescript.md
  docs/_tutorials/migration_v3.md
  docs/_tutorials/reference.md
  docs/_tutorials/using-typescript.md
  examples/socket-mode/README.md
  examples/socket-mode/app.js
  examples/socket-mode/package.json
  package.json
  src/App.spec.ts
  src/App.ts
  src/errors.ts
  src/index.ts
  src/receivers/ExpressReceiver.spec.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/verify-request.ts
  types/tsscmp.d.ts
Labels: enhancement

#754 Release v3.0.0
  package.json
Labels: release

#760 Fix broken url in docs
  docs/_advanced/receiver.md
Labels: docs

#762 Add localized Heroku deployment guide
  docs/_deployments/aws-lambda.md
  docs/_deployments/heroku.md
  docs/_deployments/ja_heroku.md
Labels: docs

#764 fixed node-slack-sdk issue 1156, socketMode connection error not bein…
  src/receivers/SocketModeReceiver.ts
Labels: bug

#768 Add Four New Workflow / Workflow Step Event Interfaces
  src/types/events/base-events.ts
Labels: TypeScript-specific, enhancement

#771 Release v3.1.0
  package.json
Labels: release

#773 Release v3.1.1
  package.json
Labels: release
