Repository slackapi/bolt-js, pull requests merged in 2021-06, with the labels that each got.

#948 Fix #947 Enable to use app.client with passed token for single workspace apps
  src/App.spec.ts
  src/App.ts
Labels: enhancement, semver:minor

#953 Fix #951 TypeScript 4.3 typing for `KnownKeys<ChatPostMessageArguments>`
  src/types/helpers.ts
  src/types/utilities.ts
Labels: TypeScript-specific, bug, semver:minor

#915 Make API response types more specific utilizing the types in web-api 6.2
  package.json
  src/WorkflowStep.ts
  src/receivers/SocketModeReceiver.ts
  src/types/utilities.ts
  types-tests/utilities.test-d.ts
Labels: TypeScript-specific, enhancement, semver:minor

#957 Fix #956 Add bot_id / bot_profile to GenericMessageEvent
  src/types/events/message-events.spec.ts
  src/types/events/message-events.ts
Labels: TypeScript-specific, bug, semver:minor

#958 Release v3.4.0
  package.json
Labels: release, semver:minor

#847 Docs for App#command regex support
  docs/_basic/listening_responding_commands.md
  docs/_basic/listening_responding_shortcuts.md
Labels: docs

#853 Fix #849 Add Japanese translation for #847
  docs/_basic/ja_listening_responding_commands.md
  docs/_basic/ja_listening_responding_shortcuts.md
Labels: docs

#961 Fix #960 by adding edited property to app_mention event payload
  src/types/events/base-events.ts
Labels: TypeScript-specific, bug

#967 Update Reference to reflect value described for processBeforeResponse
  docs/_tutorials/reference.md
Labels: bug, docs

#940 add example how to use AWSLambdaReceiver (#815)
  docs/_deployments/aws-lambda.md
  examples/deploy-aws-lambda/.gitignore
  examples/deploy-aws-lambda/README.md
  examples/deploy-aws-lambda/app.js
  examples/deploy-aws-lambda/package.json
  examples/deploy-aws-lambda/serverless.yml
Labels: area:examples, good first issue

#972 Fix #971 AwsLambdaReceiver fails to parse event.body if isBase64Encoded is true
  src/receivers/AwsLambdaReceiver.spec.ts
  src/receivers/AwsLambdaReceiver.ts
Labels: enhancement
