Repository slackapi/bolt-js, pull requests merged in 2021-02, with the labels that each got.

#777 Standardize fetchInstallation to use installQuery as argument
  docs/_basic/authenticating_oauth.md
  docs/_basic/ja_authenticating_oauth.md
  docs/_tutorials/ja_migration_v3.md
  docs/_tutorials/migration_v3.md
Labels: docs

#776 Export Reaction Interfaces
  src/types/events/base-events.ts
Labels: TypeScript-specific, bug

#783 Added channel_id_changed event
  src/types/events/base-events.ts
Labels: enhancement

#782 Update message types
  src/middleware/builtin.spec.ts
  src/types/events/message-events.ts
Labels: bug, semver:minor

#788 Release v3.2.0
  package.json
  types-tests/message.test-d.ts
Labels: release

#789 Update example apps to use @slack/bolt@3.2.0 or greater
  .gitignore
  examples/deploy-aws-lambda/package.json
  examples/deploy-heroku/package.json
  examples/socket-mode/.gitignore
  examples/socket-mode/package.json
Labels: area:examples, docs

#790 Fix events documentation code sample to use event.user
  docs/_basic/ja_listening_events.md
  docs/_basic/listening_events.md
Labels: docs

#800 Updates docs and examples about deploying to AWS Lambda
  docs/_deployments/aws-lambda.md
  examples/deploy-aws-lambda/app.js
Labels: docs

#798 Add Japanese translation to AWS Lambda deployment guide
  docs/_deployments/ja_aws-lambda.md
Labels: docs

#763 Issue 284 regex events
  src/App.spec.ts
  src/App.ts
  src/middleware/builtin.spec.ts
  src/middleware/builtin.ts
  src/types/events/base-events.ts
Labels: enhancement, semver:minor

#806 [#804] Fix AWS Lambda deploy guide using @vendia/serverless-express
  docs/_deployments/aws-lambda.md
  docs/_deployments/ja_aws-lambda.md
  examples/deploy-aws-lambda/package.json
Labels: area:examples, bug

#807 Fix incomplete logged sentence in SocketModeReciever
  src/receivers/SocketModeReceiver.ts
Labels: bug

#810 Commonize the HTML rendering for OAuth install path
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/render-html-for-install-path.ts
Labels: enhancement

#785 Fix #784 Add built-in AwsLambdaReceiver
  src/index.ts
  src/receivers/AwsLambdaReceiver.spec.ts
  src/receivers/AwsLambdaReceiver.ts
Labels: enhancement
