Repository slackapi/bolt-js, pull requests merged in 2021-11, with the labels that each got.

#1190 Fix call in aws handler to match example (and be correct)
  docs/_deployments/aws-lambda.md
Labels: docs

#1185 Fix #1148 - Adjust the app.message listener interface in TypeScript to compile the examples in documents
  src/App.spec.ts
  src/App.ts
Labels: bug, TypeScript-specific

#1183 Fix #860 Enable developers to customize the built-in receivers more
  examples/custom-properties/http.js
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
Labels: enhancement

#1193 v3.8.0 release
  package.json
Labels: release

#1195 Add the steps for safety in the release procedure
  .github/maintainers_guide.md
  .gitignore
Labels: release

#1202 Remove references to passing port to `start` method when using socket mode
  docs/_tutorials/getting_started.md
  docs/_tutorials/ja_getting_started.md
Labels: docs

#1207 Ignore query params when using customRoutes with SocketModeReceiver
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.spec.ts
  src/receivers/SocketModeReceiver.ts
Labels: bug

#1210 Adding support for HTTPReceiver.start(port: string)
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
Labels: enhancement, TypeScript-specific

#1214 add documentation how to listen to view_closed events #1010
  docs/_basic/listening_modals.md
Labels: docs

#1218 add documentation for socket mode and developer mode
  docs/_tutorials/reference.md
Labels: docs

#1225 Update git stale action
  .github/workflows/triage-issues.yml
Labels: enhancement

#1221 Add expires at in updateConversation context
  src/conversation-store.spec.ts
  src/conversation-store.ts
Labels: enhancement
