Repository slackapi/bolt-js, pull requests merged in 2021-03, with the labels that each got.

#823 Fix arguments type for App.start()
  src/App.ts
Labels: TypeScript-specific, bug

#825 Release v3.3.0
  package.json
Labels: release

#827 Fix #629 confusing debug log by ConversationStore
  src/conversation-store.ts
Labels: enhancement

#828 Add trigger_id to ViewSubmitAction interface
  src/types/view/index.ts
Labels: TypeScript-specific, enhancement, semver:patch

#830 fixed WorkflowStep StepUpdateArguments property types.
  src/WorkflowStep.ts
Labels: TypeScript-specific, bug, semver:patch

#832 Add missing message events & more type tests
  src/types/events/index.ts
  types-tests/command.test-d.ts
  types-tests/event.test-d.ts
  types-tests/message.test-d.ts
  types-tests/options.test-d.ts
  types-tests/view.test-d.ts
Labels: TypeScript-specific, enhancement

#706 adding type for plain_text_input action elements
  src/types/actions/block-action.ts
Labels: TypeScript-specific, enhancement

#835 Update the default receiver in the reference document
  docs/_tutorials/reference.md
Labels: bug, docs

#836 Update the description about processBeforeResponse in Reference document
  docs/_tutorials/reference.md
Labels: bug, docs

#844 Small clarification constraint reference
  docs/_tutorials/reference.md
Labels: docs

#843 Add JA-JP reference guide
  docs/_tutorials/reference.md
Labels: untriaged

#845 Add TypeScript Getting Started equivalent
  docs/_basic/ja_listening_actions.md
  docs/_basic/ja_listening_events.md
  docs/_basic/ja_web_api.md
  docs/_basic/listening_actions.md
  docs/_basic/listening_events.md
  docs/_basic/web_api.md
  docs/_tutorials/using-typescript.md
  examples/getting-started-typescript/.env.sample
  examples/getting-started-typescript/.gitignore
  examples/getting-started-typescript/README.md
  examples/getting-started-typescript/package.json
  examples/getting-started-typescript/src/app.ts
  examples/getting-started-typescript/src/basic.ts
  examples/getting-started-typescript/src/utils/env.ts
  examples/getting-started-typescript/src/utils/helpers.ts
  examples/getting-started-typescript/tsconfig.json
Labels: TypeScript-specific, area:examples, docs

#846 Allow command handlers to match regexes
  src/App.spec.ts
  src/App.ts
  src/middleware/builtin.spec.ts
  src/middleware/builtin.ts
Labels: enhancement

#761 Issue 281 message array support
  src/App.ts
  src/middleware/builtin.spec.ts
  src/middleware/builtin.ts
Labels: enhancement, semver:minor

#851 Add JA-JP reference
  docs/_config.yml
  docs/_tutorials/ja_reference.md
Labels: docs

#852 Fix #632 Add Japanese version of PR #626 (App Home document)
  docs/_basic/ja_authenticating_oauth.md
  docs/_basic/ja_listening_responding_options.md
  docs/_basic/ja_publishing_views.md
Labels: docs

#854 Revert "Issue 281 message array support"
  src/App.ts
  src/middleware/builtin.spec.ts
  src/middleware/builtin.ts
Labels: bug

#856 Fix #496 Add clientOptions.logger option (and improvements to other attributes too)
  codecov.yml
  src/App.ts
Labels: enhancement

#857 Fix #757 Add event type name validation & channel_type filter middleware
  src/App.spec.ts
  src/App.ts
Labels: enhancement
