Repository slackapi/bolt-js, pull requests merged in 2021-08, with the labels that each got.

#1036 ESLint Config Migration: Fixing lint errors for "no-use-before-define" rule.
  src/App.spec.ts
  src/App.ts
  src/errors.ts
  src/middleware/builtin.spec.ts
  src/receivers/ExpressReceiver.spec.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.spec.ts
  src/receivers/verify-request.ts
Labels: tests

#1039 Fix #1038 by making the AwsLambdaReceiver example TS compatible
  examples/deploy-aws-lambda/app.js
  src/App.ts
  src/receivers/AwsLambdaReceiver.spec.ts
Labels: bug

#1042 ESLint Config Migration: Fix missing function return types
  src/receivers/HTTPReceiver.ts
  src/receivers/render-html-for-install-path.ts
Labels: untriaged

#1043 ESLint Config Migration: Export a function by default in modules
  src/App.ts
  src/WorkflowStep.ts
  src/middleware/process.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/render-html-for-install-path.ts
Labels: untriaged

#1056 Fix broken markdown tables in reference docs
  docs/_tutorials/ja_reference.md
  docs/_tutorials/reference.md
Labels: docs

#1008 #999 Adds Slack Connect API event types
  src/types/events/base-events.ts
Labels: enhancement

#1046 doc: make events in the document clearer
  docs/_advanced/authorization.md
  docs/_advanced/context.md
  docs/_advanced/middleware_global.md
  docs/_basic/acknowledging_requests.md
  docs/_basic/listening_actions.md
  docs/_basic/listening_modals.md
  docs/_basic/listening_responding_commands.md
  docs/_basic/listening_responding_shortcuts.md
  docs/_basic/responding_actions.md
Labels: docs

#1055 ESLint Config Migration: Disable the only occurrences of no-nested-ternary rule violation
  src/App.ts
  src/types/events/index.ts
  src/types/options/index.ts
Labels: tests

#1066 Update deploy with aws serverless guide
  docs/_deployments/aws-lambda.md
Labels: docs

#1070 Publish
  package.json
Labels: release

#1071 updated incorrect apphome test
  src/middleware/builtin.spec.ts
Labels: tests

#1041 ESLint Config Migration: Remove no-inferrable-types rule
  .eslintrc.js
Labels: tests

#1037 ESLint Config Migration: Tweak the operator-linebreak lint rule
  .eslintrc.js
  src/App.spec.ts
  src/App.ts
  src/receivers/AwsLambdaReceiver.spec.ts
  src/receivers/AwsLambdaReceiver.ts
  src/receivers/ExpressReceiver.spec.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.ts
Labels: tests

#1032 [WIP] ESLint Config Migration: Expand import/no-internal-modules allowlist
  .eslintrc.js
Labels: enhancement, tests

#1050 ESLint Config Migration: Remove strict-boolean-expressions rule
  .eslintrc.js
Labels: tests

#1054 ESLint Config Migration: Disable max-classes-per-file rule
  .eslintrc.js
Labels: tests

#1052 ESLint Config Migration: Enum members should use PascalCase
  .eslintrc.js
Labels: tests

#1044 ESLint Config Migration: Add test-specific ruleset
  .eslintrc.js
Labels: tests

#1045 ESLint Config Migration: Allow unused vars with leading underscores
  .eslintrc.js
  src/WorkflowStep.spec.ts
  src/WorkflowStep.ts
Labels: tests

#1078 Fix #1040 Remove invalid warning logs for logger initialization
  src/App.ts
Labels: bug

#1076 Fix #1027 by removing unnecessary lines of code in ExpressReceiver
  src/receivers/ExpressReceiver.ts
Labels: bug

#891 Fix #859 Improve the way to handle authorize fn errors in built-in receivers
  src/App.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
Labels: bug, enhancement, semver:minor, tests

#1083 Fix #982 Enable developers to customize the "/slack/install" webpage content
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.spec.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/render-html-for-install-path.ts
Labels: enhancement

#1088 Fix #648 Option to disable signature verification
  src/App.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/verify-request.ts
Labels: enhancement

#1087 Fix #874: Enable using BoltJS without passing a botId
  src/middleware/builtin.spec.ts
  src/middleware/builtin.ts
Labels: bug, semver:patch

#1095 Resolve/ignore eslint warnings
  .eslintrc.js
  src/App.ts
  src/WorkflowStep.spec.ts
  src/WorkflowStep.ts
  src/conversation-store.ts
  src/helpers.ts
  src/middleware/builtin.ts
  src/receivers/AwsLambdaReceiver.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.ts
  src/test-helpers.ts
  src/types/actions/block-action.ts
  src/types/actions/workflow-step-edit.ts
  src/types/events/base-events.ts
  src/types/events/message-events.ts
  src/types/helpers.ts
  src/types/options/index.ts
  src/types/receiver.ts
  src/types/shortcuts/message-shortcut.ts
  src/types/utilities.ts
Labels: semver:patch, tests

#1097 Fix eslint warnings in getting-started-typescript app (ref #1095)
  examples/getting-started-typescript/src/app.ts
  examples/getting-started-typescript/src/basic.ts
  examples/getting-started-typescript/src/utils/env.ts
  examples/getting-started-typescript/src/utils/helpers.ts
  examples/getting-started-typescript/tsconfig.eslint.json
Labels: TypeScript-specific, area:examples
