Repository slackapi/bolt-js, pull requests merged in 2021-04, with the labels that each got.

#863 Fix #718 add tokenVerificationEnabled flag to App constructor
  src/App.spec.ts
  src/App.ts
Labels: enhancement, semver:minor

#862 Add more type tests related to #861
  types-tests/message.test-d.ts
Labels: TypeScript-specific, tests

#872 export options types and interfaces
  src/types/options/index.ts
Labels: TypeScript-specific, enhancement, semver:minor

#873 Fix a few array field definition errors in TypeScript
  src/types/actions/block-action.spec.ts
  src/types/actions/block-action.ts
  src/types/actions/interactive-message.spec.ts
  src/types/actions/interactive-message.ts
Labels: TypeScript-specific, bug, semver:minor

#877 feat: async signingSecret on ExpressReceiver
  src/receivers/ExpressReceiver.spec.ts
  src/receivers/ExpressReceiver.ts
Labels: enhancement, semver:minor

#878 Fix #720 ack(options) does not compile in TypeScript
  src/App.ts
  types-tests/options.test-d.ts
Labels: TypeScript-specific, bug, semver:minor

#879 Fix #497 Add types of state.values on modal submission
  src/types/view/index.ts
  types-tests/view.test-d.ts
Labels: TypeScript-specific, enhancement, semver:minor

#886 Docs: Fix example code for team_join event
  docs/_basic/listening_events.md
Labels: docs

#887 JA-JP user.id error
  docs/_basic/ja_listening_events.md
Labels: docs

#889 Fix #534 respond support in view_submission listeners (it works only when response_url_enabled is true)
  src/App.spec.ts
  src/App.ts
  src/types/view/index.ts
Labels: enhancement, semver:minor

#902 Fix #897 Add built-in fields to Context object type
  src/types/middleware.ts
Labels: TypeScript-specific, enhancement

#900 Fix #894 Unable to build options request objects in TypeScript
  src/middleware/builtin.ts
  src/types/options/index.spec.ts
  src/types/options/index.ts
  src/types/view/index.ts
  types-tests/options.test-d.ts
Labels: TypeScript-specific, bug
