Repository slackapi/bolt-js, pull requests merged in 2021-05, with the labels that each got.

#906 Add blocks / attachments to app_mention event interface
  src/types/events/base-events.ts
Labels: TypeScript-specific, bug, semver:minor

#912 Fix #911 TypeScript error when using builtin onlyViewActions middleware
  src/middleware/builtin.ts
  src/receivers/HTTPReceiver.ts
  types-tests/middleware.test-d.ts
Labels: TypeScript-specific, bug, semver:minor

#916 Fix typo
  docs/_basic/ja_socket_mode.md
Labels: docs

#918 Updated `ReactionRemovedEvent` type
  src/types/events/base-events.ts
  types-tests/event.test-d.ts
Labels: TypeScript-specific, enhancement, semver:patch

#920 Fix build:watch command in examples/getting-started-typescript
  examples/getting-started-typescript/package.json
Labels: area:examples, bug

#923 Add a type test verifying #922 is resolved by #878
  docs/_basic/ja_listening_responding_options.md
  docs/_basic/listening_responding_options.md
  types-tests/options.test-d.ts
Labels: TypeScript-specific, area:examples, tests

#927 Fix #925 by adding optional properties to CodedError interface
  src/errors.ts
  types-tests/error.test-d.ts
Labels: TypeScript-specific, bug, enhancement, semver:minor

#928 Fix #926 by adding more subtype ones to message event types
  src/types/events/message-events.spec.ts
  src/types/events/message-events.ts
Labels: TypeScript-specific, bug, enhancement, semver:minor

#932 Update Heroku Deploy Doc to Reflect Requirements for Socket Mode
  docs/_deployments/heroku.md
Labels: area:examples, docs

#946 [Fixes 942] Add is_bot_user_member to link_shared event
  src/types/events/base-events.ts
Labels: TypeScript-specific, enhancement, semver:minor

#938 ignore casing of HTTP headers as requested by RFC (#937)
  src/receivers/AwsLambdaReceiver.spec.ts
  src/receivers/AwsLambdaReceiver.ts
Labels: bug, semver:patch

#945 Improve storeInstallation docs
  docs/_basic/authenticating_oauth.md
  docs/_basic/ja_authenticating_oauth.md
  docs/_tutorials/ja_migration_v3.md
  docs/_tutorials/migration_v3.md
Labels: TypeScript-specific, docs

#949 Fix #935 enterprise_id in InstallationQuery can be invalid for Slack Connect channel events
  src/App.spec.ts
  src/App.ts
Labels: bug, semver:minor
