Repository slackapi/bolt-js, pull requests merged in 2022-02, with the labels that each got.

#1297 Update ngrok link to point to official guide
  docs/_tutorials/getting_started_http.md
  docs/_tutorials/ja_getting_started_http.md
Labels: bug, docs

#1302 Update SlackEvent type to include ChannelIDChangedEvent
  src/types/events/base-events.ts
Labels: enhancement

#1303 Fix #248 by adding a new option deferInitialization
  examples/custom-properties/http.js
  examples/custom-properties/package.json
  src/App.spec.ts
  src/App.ts
Labels: enhancement

#1315 Improve OAuth documentation
  docs/_basic/authenticating_oauth.md
Labels: docs

#1322 Fix #1320 plus add mising properties in events
  src/types/events/base-events.ts
Labels: bug, enhancement, TypeScript-specific

#1323 Quote add to slack URL
  src/receivers/render-html-for-install-path.ts
Labels: bug, semver:patch

#1329 Add FileInstallationStore to OAuth docs
  .github/maintainers_guide.md
  docs/_basic/authenticating_oauth.md
Labels: docs

#1328 Fix #674 Add tokens_revoked / app_uninstalled event supports
  src/App.spec.ts
  src/App.ts
Labels: bug, enhancement

#1327 Fix #1231 Redundant code path inside an if/else block in App class
  src/App.ts
Labels: enhancement

#1326 Organize the test assets
  package.json
  src/App-basic-features.spec.ts
  src/App-built-in-middleware.spec.ts
  src/App-routes.spec.ts
  src/App-workflow-steps.spec.ts
  src/WorkflowStep.spec.ts
  src/helpers.spec.ts
  src/middleware/builtin.spec.ts
  src/receivers/AwsLambdaReceiver.spec.ts
  src/types/actions/block-action.spec.ts
  src/types/actions/interactive-message.spec.ts
  src/types/events/message-events.spec.ts
  src/types/options/index.spec.ts
Labels: enhancement, tests

#1340 export EnvelopedEvent interface
  src/types/events/index.ts
Labels: enhancement, semver:minor
