Repository slackapi/bolt-js, pull requests merged in 2022-09, with the labels that each got.

#1575 Fixed trivial typo
  .github/maintainers_guide.md
Labels: docs

#1577 Set @types/node to set version 18.7.15
  package.json
Labels: enhancement

#1578 Add dependabot version management
  .github/dependabot.yml
  package.json
Labels: enhancement

#1592 Corrects issue with referencing get-manifest-data.js file from get-maniftest hook
  package.json
  src/cli/hook-utils/get-manifest-data.js
Labels: bug, semver:patch

#1593 Publish
  package.json
Labels: release

#1565 Add next-gen beta documentation
  docs/_config.yml
  docs/_future/app_manifests.md
  docs/_future/built_in_functions.md
  docs/_future/create_new_app.md
  docs/_future/custom_functions.md
  docs/_future/deploy_your_app.md
  docs/_future/error_troubleshooting.md
  docs/_future/feedback.md
  docs/_future/getting_started_future.md
  docs/_future/migrate_existing_app.md
  docs/_future/triggers.md
  docs/_future/workflows.md
  docs/_includes/sidebar.html
  docs/_layouts/default.html
  docs/_steps/adding_editing_workflow_step.md
  docs/_steps/creating_workflow_step.md
  docs/_steps/executing_workflow_steps.md
  docs/_steps/saving_workflow_step.md
  docs/_steps/workflow_steps_overview.md
  docs/assets/beta-tos-future.png
  docs/assets/style.css
  docs/assets/take-your-time-demo.gif
  docs/assets/take-your-time-modal.png
  docs/assets/take-your-time-open-modal-popup.png
  docs/assets/take-your-time-open-modal.gif
  docs/assets/take-your-time-open-modal.png
Labels: docs

#1594 Bump .ruby-version from 2.7.1 to 2.7.4
  docs/.ruby-version
Labels: docs, dependencies

#1601 Add in information about custom HTTP routes to docs
  docs/_advanced/custom_routes.md
  docs/_advanced/ja_custom_routes.md
Labels: docs

#1603 Update getting started guide, migrate create new app guide, and rearrange nav (next gen)
  docs/_future/app_manifests.md
  docs/_future/built_in_functions.md
  docs/_future/custom_functions.md
  docs/_future/deploy_your_app.md
  docs/_future/error_troubleshooting.md
  docs/_future/feedback.md
  docs/_future/getting_started_future.md
  docs/_future/migrate_existing_app.md
  docs/_future/request_time_off_tutorial.md
  docs/_future/triggers.md
  docs/_future/workflows.md
  docs/assets/hello-world-demo.gif
  docs/assets/hello-world-modal.png
Labels: docs
