Repository slackapi/bolt-js, pull requests merged in 2022-07, with the labels that each got.

#1511 feat: add `isEnterpriseInstall` to Context
  src/App.ts
  src/middleware/builtin.spec.ts
  src/types/middleware.ts
Labels: enhancement, semver:minor

#1505 Allow passing additional types for Global and Middleware Context
  src/App-context-types.spec.ts
  src/App.ts
  src/types/middleware.ts
Labels: enhancement, TypeScript-specific

#1508 Adding Message Metadata Support to Bolt JS
  examples/message-metadata/.gitignore
  examples/message-metadata/README.md
  examples/message-metadata/app-manifest.json
  examples/message-metadata/app.js
  examples/message-metadata/package.json
  package.json
  src/types/events/base-events.ts
  src/types/events/message-events.spec.ts
  src/types/events/message-events.ts
Labels: enhancement

#1518 Publish @slack/bolt@3.12.0
  package.json
Labels: semver:minor, release

#1524 Adds JP translation for processBeforeResponse & AWS guide
  docs/_deployments/aws-lambda.md
  docs/_deployments/ja_aws-lambda.md
  docs/_tutorials/ja_reference.md
Labels: docs

#1526 Updates links and adds anchors in JP and EN docs
  docs/_deployments/aws-lambda.md
  docs/_deployments/heroku.md
  docs/_deployments/ja_aws-lambda.md
  docs/_deployments/ja_heroku.md
  docs/_includes/sidebar.html
  docs/_tutorials/getting_started.md
  docs/_tutorials/getting_started_http.md
  docs/_tutorials/hubot_migration.md
  docs/_tutorials/ja_getting_started.md
  docs/_tutorials/ja_getting_started_http.md
  docs/_tutorials/ja_hubot_migration.md
  docs/_tutorials/ja_migration_v2.md
  docs/_tutorials/ja_migration_v3.md
  docs/_tutorials/ja_reference.md
  docs/_tutorials/ja_using-typescript.md
  docs/_tutorials/migration_v2.md
  docs/_tutorials/migration_v3.md
  docs/_tutorials/reference.md
  docs/_tutorials/using-typescript.md
Labels: docs

#1528 Fix #1509 HTTPReceiver does not immediately respond to an invalid signature request (no response instead)
  src/receivers/HTTPModuleFunctions.ts
Labels: bug, semver:patch

#1519 Updated maintainers guide to add more clarity
  .github/maintainers_guide.md
Labels: docs

#1530 Fix manifest read issue
  src/Manifest.ts
  src/cli/get-manifest.js
  src/cli/hook-utils/manifest.js
Labels: enhancement
