Repository slackapi/bolt-js, pull requests merged in 2022-05, with the labels that each got.

#1441 Upgrade socket-mode dependency to the latest minor
  package.json
Labels: enhancement

#1447 removed nonexistent link from `Deployments` sidebar
  docs/_includes/sidebar.html
Labels: docs, semver:patch

#1446 Move scripts to `bin` field of package.json for cli hackery
  package.json
  src/cli/get-hooks.js
  src/cli/manifest.js
  src/cli/manifest.ts
  src/cli/start.js
Labels: enhancement, discussion

#1452 Cancel LambdaReceiver and HTTPResponseAck timeout
  src/receivers/AwsLambdaReceiver.ts
  src/receivers/HTTPResponseAck.spec.ts
  src/receivers/HTTPResponseAck.ts
Labels: bug, semver:patch

#1448 Adding support for new user-change events with types
  src/types/events/base-events.ts
  types-tests/event.test-d.ts
Labels: enhancement, semver:minor

#1455 Fix #1454 Missing type declarations in view objects
  src/types/view/index.ts
Labels: bug, TypeScript-specific

#1459 Update link to reference documentation in App.ts
  src/App.ts
Labels: enhancement, docs
