Repository slackapi/bolt-js, pull requests merged in 2022-03, with the labels that each got.

#1348 Update beta releasing steps for maintainers
  .github/maintainers_guide.md
Labels: docs

#1369 Log httpServer.close error only when defined
  src/receivers/SocketModeReceiver.ts
Labels: enhancement

#1381 Fix #1380 by adding more event payload types
  src/types/events/base-events.ts
Labels: bug, TypeScript-specific

#1384 Deploy the App to Heroku with one click
  app.json
  examples/deploy-heroku/README.md
Labels: enhancement, docs

#1390 Add Socket Mode OAuth example app
  examples/socket-mode-oauth/.gitignore
  examples/socket-mode-oauth/app.js
  examples/socket-mode-oauth/package.json
Labels: docs, area:examples

#1359 Fix #1358 Expose common utilities for building HTTP module based receivers
  examples/custom-receiver/.gitignore
  examples/custom-receiver/README.md
  examples/custom-receiver/link.sh
  examples/custom-receiver/package.json
  examples/custom-receiver/src/FastifyReceiver.ts
  examples/custom-receiver/src/KoaReceiver.ts
  examples/custom-receiver/src/fastify-main.ts
  examples/custom-receiver/src/koa-main.ts
  examples/custom-receiver/tsconfig.eslint.json
  examples/custom-receiver/tsconfig.json
  src/errors.ts
  src/index.ts
  src/receivers/BufferedIncomingMessage.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPModuleFunctions.spec.ts
  src/receivers/HTTPModuleFunctions.ts
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/HTTPResponseAck.ts
  src/receivers/http-utils.ts
  src/receivers/render-html-for-install-path.ts
  src/receivers/verify-request.ts
  types-tests/error.test-d.ts
Labels: enhancement

#1392 Fix #1385 Create a signature validation function that is not tied to the request
  src/index.ts
  src/receivers/HTTPModuleFunctions.ts
  src/receivers/verify-request.spec.ts
  src/receivers/verify-request.ts
Labels: enhancement

#1393 Fix #1376 CustomRoute interface should be accessible from developers
  src/index.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/custom-routes.ts
Labels: enhancement

#1391 Fix #1335 Proper use of state parameter for the OAuth CSRF protection
  examples/oauth-express-receiver/app.js
  examples/oauth-express-receiver/link.sh
  examples/socket-mode-oauth/link.sh
  package.json
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.spec.ts
  src/receivers/SocketModeReceiver.ts
Labels: bug, enhancement

#1401 Add more unit tests
  src/App-basic-features.spec.ts
  src/receivers/AwsLambdaReceiver.spec.ts
  src/receivers/HTTPResponseAck.spec.ts
Labels: enhancement

#1400 Fix #1397 bolt-js does not accept ssl_check requests properly
  src/receivers/HTTPModuleFunctions.spec.ts
  src/receivers/HTTPModuleFunctions.ts
Labels: bug

#1403 Adding unit test coverage to the HTTPResponseAck class
  src/receivers/HTTPResponseAck.spec.ts
Labels: tests

#1407 More ExpressReceiver tests
  src/App-basic-features.spec.ts
  src/App-built-in-middleware.spec.ts
  src/receivers/ExpressReceiver.spec.ts
  src/receivers/ExpressReceiver.ts
Labels: tests

#1406 Add more error handlers to ExpressReceiver
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPModuleFunctions.ts
Labels: enhancement

#1405 Fix #1404 SocketModeReceiver app process exits when any of its event listeners throws an exception
  examples/socket-mode/app.js
  examples/socket-mode/link.sh
  src/index.ts
  src/receivers/HTTPModuleFunctions.ts
  src/receivers/SocketModeFunctions.spec.ts
  src/receivers/SocketModeFunctions.ts
  src/receivers/SocketModeReceiver.ts
Labels: bug

#1396 Publish @slack/bolt@3.11.0
  package.json
Labels: semver:minor, release
