Repository slackapi/bolt-js, pull requests merged in 2022-01, with the labels that each got.

#1254 Export more message event types
  src/types/events/index.ts
Labels: enhancement, TypeScript-specific

#1273 Upgrade underlying oauth, types, web-api packages
  package.json
Labels: release

#1250 Improve App initialization error logs + docs
  docs/_basic/authenticating_oauth.md
  src/App.ts
Labels: enhancement

#1277 Publish @slack/bolt-js@3.9.0
  package.json
Labels: release

#1287 Publish
  package.json
Labels: release

#1288 Add userScopes to the OAuth docs for BoltJS
  docs/_basic/authenticating_oauth.md
Labels: docs

#1295 Add JP transln for userScopes property, add missing comma
  docs/_basic/authenticating_oauth.md
  docs/_basic/ja_authenticating_oauth.md
Labels: docs
