Repository slackapi/bolt-js, pull requests merged in 2022-06, with the labels that each got.

#1473 Fix #1472 say argument does not exist for pin_* events in TS
  src/types/events/base-events.ts
  types-tests/event.test-d.ts
Labels: bug, TypeScript-specific

#1476 Fix say absence in TS for reaction_ events (ref #1473)
  src/types/events/base-events.ts
  types-tests/event.test-d.ts
Labels: bug, TypeScript-specific

#1481 Add more logs for error patterns in AwsLambdaReceiver
  src/receivers/AwsLambdaReceiver.ts
Labels: enhancement

#1483 Fix markdown error in a Japanese document
  docs/_tutorials/ja_getting_started.md
Labels: docs

#1482 Fix #1478 ack() is not accessible in global middleware in TypeScript
  src/App-basic-features.spec.ts
  src/types/events/index.ts
  types-tests/middleware.test-d.ts
Labels: bug, TypeScript-specific

#1484 Publish @slack/bolt@3.11.2
  package.json
Labels: semver:patch, release

#1490 Fix #1488 Incorrect types with ViewUpdateResponseAction and ViewPushResponseAction
  src/App-routes.spec.ts
  src/types/view/index.ts
Labels: bug, TypeScript-specific

#1492 fixed warning typo
  src/receivers/render-html-for-install-path.ts
Labels: bug, semver:patch

#1503 Update error msg on stale request
  src/receivers/HTTPModuleFunctions.spec.ts
  src/receivers/verify-request.spec.ts
  src/receivers/verify-request.ts
Labels: enhancement, docs
