Repository slackapi/bolt-js, pull requests merged in 2022-08, with the labels that each got.

#1537 Update get-manifest hook and Manifest exports
  package.json
  src/Manifest.ts
  src/cli/hook-utils/manifest.js
  src/cli/hook-utils/manifest.spec.js
  src/cli/run.ts
  src/index.ts
Labels: enhancement

#1540 Fix issue with parsing manifest module with object functions
  package.json
  src/Manifest.ts
  src/cli/get-manifest.js
Labels: bug

#1545 Delete unnecessary character from doc
  docs/_tutorials/ja_migration_v2.md
Labels: docs

#1553 Update SocketModeFunctions.ts
  src/receivers/SocketModeFunctions.ts
Labels: bug

#1556 Delete CHANGELOG.md
  CHANGELOG.md
Labels: enhancement

#1557 Fix misspellings / typos detected by WebStorm IDE
  .gitignore
  src/App.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPModuleFunctions.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/verify-request.ts
  src/types/view/index.ts
Labels: bug

#1567 Support SlackFunction and Function Localized Interactivity handling
  package.json
  src/App-slack-function.spec.ts
  src/App.ts
  src/SlackFunction.spec.ts
  src/SlackFunction.ts
  src/cli/get-manifest.js
  src/cli/hook-utils/manifest.js
  src/cli/run.ts
  src/errors.ts
  src/middleware/builtin.ts
  src/types/actions/block-action.ts
  src/types/actions/dialog-action.ts
  src/types/functions/index.ts
  src/types/middleware.ts
  src/types/view/index.ts
  tsconfig.json
Labels: enhancement, semver:major
