Repository slackapi/bolt-js, pull requests merged in 2023-05, with the labels that each got.

#1821 Fix #1819 Add metadata to response_url params
  src/types/utilities.spec.ts
  src/types/utilities.ts
Labels: bug, TypeScript-specific

#1838 Bump @slack/types version to ^2.8.0
  package.json
Labels: semver:patch, dependencies

#1844 Improve the docs for better TypeScript compatibility
  docs/_advanced/context.md
  docs/_advanced/error_handling.md
  docs/_advanced/ja_context.md
  docs/_advanced/ja_error_handling.md
  docs/_advanced/ja_middleware_listener.md
  docs/_advanced/middleware_listener.md
  docs/_basic/acknowledging_requests.md
  docs/_basic/authenticating_oauth.md
  docs/_basic/ja_acknowledging_requests.md
  docs/_basic/ja_authenticating_oauth.md
  docs/_basic/ja_listening_events.md
  docs/_basic/ja_listening_messages.md
  docs/_basic/ja_responding_actions.md
  docs/_basic/ja_updating_pushing_modals.md
  docs/_basic/ja_web_api.md
  docs/_basic/listening_events.md
  docs/_basic/listening_messages.md
  docs/_basic/responding_actions.md
  docs/_basic/updating_pushing_modals.md
  docs/_basic/web_api.md
Labels: docs, TypeScript-specific

#1845 Simplify reaction_added/removed event's item type
  src/types/events/base-events.ts
Labels: bug, TypeScript-specific

#1849 Fix #1512 Remove say from SlackShortcutMiddlewareArgs for GlobalSho…
  src/types/shortcuts/index.ts
  types-tests/shortcut.test-d.ts
Labels: bug, TypeScript-specific, cla:signed

#1853 Expose user ID in context
  src/App.ts
  src/types/middleware.ts
Labels: enhancement, cla:signed
