Repository slackapi/bolt-js, pull requests merged in 2023-10, with the labels that each got.

#1940 fix: options constraint has wrong type definition
  src/App-context-types.spec.ts
  src/App-routes.spec.ts
  src/App.ts
  src/middleware/builtin.ts
Labels: bug, TypeScript-specific, cla:signed

#1963 Add rich_text_input block payload support
  package.json
  src/types/actions/block-action.ts
  src/types/view/index.ts
Labels: enhancement, TypeScript-specific

#1972 Allow a custom `SocketModeReceiver` to be used with Socket Mode
  src/App-basic-features.spec.ts
  src/App.ts
Labels: enhancement, semver:patch

#1973 Include an example of using middleware with the `ExpressReceiver`
  docs/_advanced/custom_routes.md
  docs/_advanced/ja_custom_routes.md
Labels: docs, semver:patch
