Repository slackapi/bolt-js, pull requests merged in 2023-09, with the labels that each got.

#1955 Expose useful functions
  src/App.ts
  src/helpers.spec.ts
  src/helpers.ts
Labels: enhancement, semver:patch

#1956 Release: @slack/bolt@3.14.0
  package.json
Labels: release

#1961 Remove beta documentation
  docs/_config.yml
  docs/_future/app_manifests.md
  docs/_future/built_in_functions.md
  docs/_future/custom_functions.md
  docs/_future/deploy_your_app.md
  docs/_future/error_troubleshooting.md
  docs/_future/feedback.md
  docs/_future/getting_started_future.md
  docs/_future/request_time_off_tutorial.md
  docs/_future/setup_existing_app.md
  docs/_future/triggers.md
  docs/_future/workflows.md
  docs/_includes/sidebar.html
  docs/_steps/workflow_steps_overview.md
  docs/assets/beta-tos-future.png
  docs/assets/hello-world-demo.gif
  docs/assets/hello-world-modal.png
  docs/assets/style.css
  docs/assets/take-your-time-demo.gif
  docs/assets/take-your-time-modal.png
  docs/assets/take-your-time-open-modal-popup.png
  docs/assets/take-your-time-open-modal.gif
  docs/assets/take-your-time-open-modal.png
Labels: docs
