Repository slackapi/bolt-js, pull requests merged in 2023-11, with the labels that each got.

#1986 Upgrade axios
  package.json
Labels: cla:signed

#1992 Fix link in docs
  docs/_basic/listening_actions.md
Labels: docs, cla:missing

#1994 Update mocha and web-api dependencies
  package.json
Labels: security, semver:patch

#1996 Release @slack/bolt@3.15.0
  package.json
Labels: semver:minor, release

#2004 Complete every matrix test regardless of adjacent failures
  .github/workflows/ci-build.yml
Labels: semver:patch, tests
