Repository slackapi/bolt-js, pull requests merged in 2023-03, with the labels that each got.

#1781 Fix #1780 by upgrading axios version to the latest
  package.json
Labels: dependencies

#1787 Fix typo in japanese docs: concepts#logging
  docs/_advanced/ja_logging.md
Labels: docs

#1785 Fix #1325 Added support for dynamic custom paths
  package.json
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/ParamsIncomingMessage.ts
  src/receivers/SocketModeReceiver.spec.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/custom-routes.ts
Labels: enhancement, semver:minor
