Repository slackapi/bolt-js, pull requests merged in 2023-08, with the labels that each got.

#1916 Fixes failing tests: block_actions.user.name is optional
  .github/workflows/ci-build.yml
  package.json
  src/receivers/AwsLambdaReceiver.spec.ts
  src/receivers/AwsLambdaReceiver.ts
  src/receivers/ExpressReceiver.spec.ts
  src/receivers/ExpressReceiver.ts
  src/receivers/HTTPModuleFunctions.spec.ts
  src/receivers/HTTPModuleFunctions.ts
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/HTTPResponseAck.spec.ts
  src/receivers/HTTPResponseAck.ts
  src/receivers/SocketModeReceiver.spec.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/http-utils.ts
  src/receivers/verify-request.spec.ts
  src/receivers/verify-request.ts
  src/types/actions/block-action.spec.ts
  src/types/actions/block-action.ts
Labels: bug, semver:patch, tests, TypeScript-specific

#1921 Release @slack/bolt@3.13.3
  package.json
Labels: release

#1928 add typings for timepicker
  src/types/actions/block-action.ts
Labels: enhancement, TypeScript-specific, cla:signed

#1937 Upload code coverage reports using the Codecov GitHub Action
  .github/workflows/ci-build.yml
  package.json
Labels: semver:patch, tests, dependencies
