Repository slackapi/bolt-js, pull requests merged in 2023-12, with the labels that each got.

#2006 Prevent sending response headers if already sent in default error han…
  src/receivers/HTTPModuleFunctions.ts
Labels: bug, enhancement, semver:patch, cla:signed

#2017 Support for `style.code` properties on rich text elements (updates `@slack/types` to 2.11 and `@slack/web-api` to 6.11)
  package.json
Labels: semver:minor, TypeScript-specific

#2018 Publish v3.17.0
  package.json
Labels: semver:minor, TypeScript-specific, release
