Repository slackapi/bolt-js, pull requests merged in 2023-04, with the labels that each got.

#1792 Test against node 18.x
  .github/workflows/ci-build.yml
Labels: tests

#1790 Fix #1758 Correct type definitions for `OptionGroups` and `*Options` types
  src/types/options/index.ts
  types-tests/options.test-d.ts
Labels: bug, semver:patch

#1796 Remove legacy tag
  docs/.ruby-version
  docs/_includes/sidebar.html
  docs/_steps/adding_editing_workflow_step.md
  docs/_steps/creating_workflow_step.md
  docs/_steps/executing_workflow_steps.md
  docs/_steps/saving_workflow_step.md
  docs/_steps/workflow_steps_overview.md
Labels: docs

#1791 Add documentation for dynamic route parameters in custom routes
  docs/_advanced/custom_routes.md
  docs/_advanced/ja_custom_routes.md
Labels: docs

#1797 Add line numbers to docs
  docs/.markdownlint.yml
  docs/_config.yml
  docs/assets/style.css
Labels: docs

#1802 Upgrade the OAuth module to the latest
  package.json
  src/App.ts
Labels: enhancement, dependencies

#1806 Fix #1805 Include headers in the request object of custom route handlers
  docs/_advanced/custom_routes.md
  docs/_advanced/ja_custom_routes.md
  src/receivers/HTTPReceiver.spec.ts
  src/receivers/HTTPReceiver.ts
  src/receivers/SocketModeReceiver.spec.ts
  src/receivers/SocketModeReceiver.ts
Labels: bug, semver:patch

#1818 Release: @slack/bolt@3.13.1
  package.json
Labels: release
