Repository slackapi/bolt-js, pull requests merged in 2023-07, with the labels that each got.

#1890 fix: added missing user type in TeamJoinEvent
  src/types/events/base-events.ts
Labels: bug, TypeScript-specific, cla:signed

#1894 Move node version to devDependencies
  package.json
Labels: enhancement

#1895 Release @slack/bolt@3.13.2
  package.json
Labels: release

#1897 Update steps for releasing a new version in the maintainers guide
  .github/maintainers_guide.md
Labels: docs

#1910 Add missing user object member to type BlockAction
  src/types/actions/block-action.ts
Labels: bug, TypeScript-specific, cla:signed
