Repository slackapi/bolt-js, pull requests merged in 2024-09, with the labels that each got.

#2226 fix: tsconfig - skip checking dependency d.ts files
  tsconfig.json
Labels: semver:patch, tests, TypeScript-specific

#2227 chore: group docusaurus dependencies
  .github/dependabot.yml
Labels: docs, dependencies

#2235 ci: add typescript example integration testing
  .github/workflows/samples.yml
  examples/getting-started-typescript/src/app.ts
  examples/getting-started-typescript/src/basic.ts
Labels: semver:patch, tests, TypeScript-specific, area:examples

#2236 chore(release): public @slack/bolt@3.21.2
  package.json
Labels: release

#2239 Link to JS release notes
  docs/sidebars.js
Labels: cla:missing

#2245 fix: re-export EnvelopedEvent
  src/types/events/index.ts
Labels: bug, semver:patch, TypeScript-specific

#2251 chore(deps): upgrade `path-to-regexp` to address a security vulnerability
  .github/workflows/ci-build.yml
  package.json
  tsconfig.json
Labels: security, semver:patch, dependencies

#2252 Publish `@slack/bolt@3.21.4`
  package.json
Labels: security, semver:patch, release

#2260 typo: update error link in App.ts
  src/App.ts
Labels: cla:signed

#2270 Upgrade express version
  package.json
Labels: cla:signed

#2273 chore(deps): bump @slack/web-api from 6.12.1 to 6.13.0
  package.json
Labels: semver:minor, dependencies

#2274 chore(release): publish @slack/bolt@3.22.0
  package.json
Labels: semver:minor, release
