Repository slackapi/bolt-js, pull requests merged in 2024-11, with the labels that each got.

#2314 Publish `@slack/bolt@4.1.0`
  package.json
Labels: release

#2283 feat: expose auto acknowledgement flag on the `function` handler
  src/App.ts
  src/CustomFunction.ts
  src/middleware/builtin.ts
  src/types/events/index.ts
  src/types/middleware.ts
  src/types/utilities.ts
  test/types/function.test-d.ts
  test/unit/App/middleware.spec.ts
  test/unit/App/routing-function.spec.ts
  test/unit/CustomFunction.spec.ts
  test/unit/helpers/app.ts
  test/unit/helpers/events.ts
  test/unit/middleware/builtin.spec.ts
Labels: enhancement, semver:minor

#2325 [#2319] Fix Assistant utility types
  docs/src/css/custom.css
  src/Assistant.ts
  test/types/assistant.test-d.ts
Labels: bug, semver:patch, TypeScript-specific

#2331 Docs: Tutorial for assistant app
  docs/content/tutorials/ai-assistant.md
  docs/sidebars.js
Labels: docs

#2339 docs: add xapp section
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/getting-started.mdx
Labels: docs, cla:signed

#2338 test: improve test around routing and acknowledging
  test/unit/App/middleware.spec.ts
  test/unit/App/middlewares/arguments.spec.ts
  test/unit/App/middlewares/global.spec.ts
  test/unit/App/middlewares/ignore-self.spec.ts
  test/unit/App/middlewares/listener.spec.ts
  test/unit/App/routing-action.spec.ts
  test/unit/App/routing-assistant.spec.ts
  test/unit/App/routing-command.spec.ts
  test/unit/App/routing-event.spec.ts
  test/unit/App/routing-message.spec.ts
  test/unit/App/routing-options.spec.ts
  test/unit/App/routing-shortcut.spec.ts
  test/unit/App/routing-view.spec.ts
  test/unit/middleware/builtin.spec.ts
Labels: tests

#2346 Publish `@slack/bolt@4.1.1`
  package.json
Labels: release
