Repository slackapi/bolt-js, pull requests merged in 2024-10, with the labels that each got.

#2277 Bolt v4 addendum: stricter typing of AWS API Gateway payloads
  src/receivers/AwsLambdaReceiver.ts
Labels: enhancement, semver:major, TypeScript-specific

#2285 fix: do not log ack timeout error if aws receiver has no registered handlers
  src/receivers/AwsLambdaReceiver.ts
  test/unit/receivers/AwsLambdaReceiver.spec.ts
Labels: bug, semver:patch

#2286 Add support for Agents/Assistants
  src/App.ts
  src/Assistant.spec.ts
  src/Assistant.ts
  src/AssistantThreadContextStore.spec.ts
  src/AssistantThreadContextStore.ts
  src/errors.ts
  src/index.ts
Labels: enhancement

#2294 Publish `@slack/bolt@v4.0.0`
  package.json
Labels: semver:major, release

#2298 Fix a bug where parsing assistant thread message event fails for beta feature enabled apps
  src/Assistant.ts
Labels: bug, semver:patch

#2300 [FIX]: Include metadata with Assistant `say` util
  src/Assistant.ts
  test/unit/Assistant.spec.ts
Labels: enhancement

#2305 chore: remove old inapplicable gemfile from docs
  docs/.gitignore
  docs/Gemfile.lock
Labels: docs

#2308 Add `title` to setSuggestedPrompts utility
  docs/docusaurus.config.js
  docs/sidebars.js
  src/Assistant.ts
  test/unit/Assistant.spec.ts
Labels: enhancement

#2310 docs: general page cleanup
  docs/content/concepts/actions.md
  docs/content/concepts/authorization.md
  docs/content/concepts/custom-routes.md
  docs/content/concepts/custom-steps.md
  docs/content/concepts/deferring-initialization.md
  docs/content/concepts/error-handling.md
  docs/content/concepts/listener-middleware.md
  docs/content/concepts/logging.md
  docs/content/concepts/message-sending.md
  docs/content/concepts/receiver.md
  docs/content/concepts/select-menu-options.md
  docs/content/concepts/shortcuts.md
  docs/content/concepts/socket-mode.md
  docs/content/concepts/updating-pushing-views.md
  docs/content/concepts/view-submissions.md
  docs/content/concepts/web-api.md
  docs/content/deployments/aws-lambda.md
  docs/content/deployments/heroku.md
  docs/content/getting-started.mdx
  docs/content/legacy/conversation-store.md
  docs/content/legacy/hubot-migration.md
  docs/content/legacy/steps-from-apps.md
  docs/content/migration/migration-v2.md
  docs/content/migration/migration-v3.md
  docs/content/migration/migration-v4.md
  docs/docusaurus.config.js
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/actions.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/authenticating-oauth.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/custom-routes.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/error-handling.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/global-middleware.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/listener-middleware.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/logging.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/message-listening.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/message-sending.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/shortcuts.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/socket-mode.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/updating-pushing-views.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/view-submissions.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/web-api.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/deployments/aws-lambda.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/deployments/heroku.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/getting-started.mdx
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/legacy/hubot-migration.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/legacy/steps-from-apps.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/migration/migration-v2.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/migration/migration-v3.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/reference.md
Labels: docs

#2311 Docs: salesforce compliance adjustment
  docs/README.md
  docs/docusaurus.config.js
  docs/footerConfig.js
  docs/navbarConfig.js
Labels: docs
