Repository slackapi/bolt-js, pull requests merged in 2024-06, with the labels that each got.

#2130 docs: deprecate Steps from Apps docs
  docs/_config.yml
  docs/_includes/sidebar.html
  docs/_layouts/default.html
  docs/_steps/workflow_steps_overview.md
  docs/assets/style.css
Labels: docs

#2134 ButtonAction value field not required
  src/types/actions/block-action.ts
Labels: bug, semver:patch, TypeScript-specific

#2136 docs: add JSDoc to and list out all available builtin middleware functions in the docs
  docs/_advanced/middleware_global.md
  docs/_advanced/middleware_listener.md
  docs/_tutorials/reference.md
  src/middleware/builtin.ts
Labels: docs, semver:patch

#2141 fix(types): return void promises from the express receiver middleware parser
  src/receivers/ExpressReceiver.ts
Labels: bug, semver:patch, TypeScript-specific, dependencies

#2140 ci(test): perform unit testing against node version 22
  .github/workflows/ci-build.yml
Labels: semver:patch, tests

#2142 chore(release): tag version @slack/bolt@3.19.0
  package.json
Labels: semver:minor, release
