Repository slackapi/bolt-js, pull requests merged in 2024-07, with the labels that each got.

#2155 Add missing Events API payload types
  src/types/events/base-events.ts
Labels: enhancement, TypeScript-specific

#2154 Add an optional handler for invalid request signature error
  src/receivers/AwsLambdaReceiver.spec.ts
  src/receivers/AwsLambdaReceiver.ts
Labels: enhancement, semver:minor, cla:signed

#2160 Add missing properties in app_mention event payload
  src/types/events/base-events.ts
Labels: bug, TypeScript-specific

#2164 fix: add ts to PinnedMessageItem interface
  src/types/events/base-events.ts
Labels: enhancement, semver:minor, TypeScript-specific, cla:signed

#2166 fix: add missing fields in ChannelCreatedEvent
  src/types/events/base-events.ts
Labels: cla:signed

#2169 Fix broken link in "external select" section
  docs/_basic/ja_listening_responding_options.md
  docs/_basic/listening_responding_options.md
Labels: docs, semver:patch, cla:signed

#2178 docs - add manual redirects scripts
  docs/README.md
  docs/docusaurus.config.js
  docs/redirects-hashes.js
  docs/redirects-pages.js
  docs/redirects.js
Labels: bug, docs
