Repository slackapi/bolt-js, pull requests merged in 2024-08, with the labels that each got.

#2179 Docs: Adds landing page and redirects
  docs/README.md
  docs/content/index.md
  docs/docusaurus.config.js
  docs/i18n/ja-jp/README.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/index.md
  docs/package-lock.json
  docs/package.json
  docs/redirects-hashes.js
  docs/redirects-pages.js
  docs/sidebars.js
  docs/src/css/custom.css
Labels: docs

#2180 Docs - fixes README image link
  README.md
Labels: docs

#2181 Docs: remove superfluous files
  docs/README.md
  docs/content/Changelog.md
  docs/i18n/ja-jp/README.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/custom-functions/creating-custom-functions.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/custom-functions/defining-custom-functions.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/custom-functions/listening-to-custom-functions.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/custom-functions/responding-to-interactivity.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/index.md
  docs/sidebars.js
Labels: docs

#2183 Fix Bold Text Rendering Issue
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/deployments/aws-lambda.md
Labels: docs, cla:signed

#2191 docs: adds google analytics tag
  docs/docusaurus.config.js
Labels: docs

#2194 chore(deps): bump axios to 1.7.3 to address CVE
  package.json
Labels: security, semver:patch, dependencies

#2195 Publish `@slack/bolt@3.20.0`
  package.json
Labels: semver:minor, release

#2128 Fixes and polish for stable release
  package.json
  src/App.ts
  src/CustomFunction.spec.ts
  src/CustomFunction.ts
  src/errors.ts
  src/middleware/builtin.ts
  src/middleware/process.ts
  src/types/actions/index.ts
  src/types/events/base-events.ts
  src/types/events/index.ts
  src/types/helpers.ts
  src/types/middleware.ts
  tsconfig.eslint.json
  types-tests/event.test-d.ts
Labels: enhancement, cla:signed

#2200 [Bug] Fix chained function actions
  src/App.ts
Labels: bug

#2201 chore(deps): bump axios to 1.7.4 to address CVE
  package.json
Labels: security, semver:patch, dependencies, cla:signed

#2199 chore: purge the "workflow step" terminology
  docs/content/reference.md
  docs/content/steps/adding-editing-steps.md
  docs/content/steps/creating-steps.md
  docs/content/steps/executing-steps.md
  docs/content/steps/saving-steps.md
  docs/content/steps/steps.md
  docs/sidebars.js
  src/WorkflowStep.ts
  src/types/actions/workflow-step-edit.ts
  src/types/view/index.ts
Labels: docs

#2202 Remote functions: typescript integration test with bolt-ts-starter-template
  .github/workflows/samples.yml
Labels: tests

#2204 Publish `@slack/bolt@3.21.0`
  package.json
Labels: release

#2205 ci: add bolt-ts-custom-function-template to list of test samples
  .github/workflows/samples.yml
Labels: tests

#2198 docs: document custom step usage
  README.md
  docs/content/basic/custom-steps.md
  docs/content/custom-functions/creating-custom-functions.md
  docs/content/custom-functions/defining-custom-functions.md
  docs/content/custom-functions/listening-to-custom-functions.md
  docs/content/custom-functions/responding-to-interactivity.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/basic/custom-steps.md
  docs/sidebars.js
Labels: docs

#2207 chore(deps): set a minimum @slack/web-api@^6.12.1 to address CVE-2024-39338
  package.json
Labels: security, semver:patch, dependencies

#2208 chore(release): publish @slack/bolt@3.21.1
  package.json
Labels: semver:patch, release

#2209 docs(fix): direct relative link to docs documentation
  .github/maintainers_guide.md
Labels: docs, semver:patch

#2210 style: remove an extra space from the pull request template
  .github/pull_request_template.md
Labels: semver:patch

#2214 fix: pass a no-op `next` function to the last listener middleware
  src/App-built-in-middleware.spec.ts
  src/App.ts
Labels: bug, semver:patch

#2220 docs: replace hard-coded state secret in examples and docs with use of an environment variable
  docs/content/basic/authenticating-oauth.md
  docs/content/basic/socket-mode.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/basic/authenticating-oauth.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/basic/socket-mode.md
  examples/oauth-express-receiver/README.md
  examples/oauth-express-receiver/app.js
  examples/oauth/README.md
  examples/oauth/app.js
  examples/socket-mode-oauth/app.js
  examples/socket-mode/README.md
  examples/socket-mode/app.js
Labels: docs

#2221 fix: remove please-upgrade-node
  package.json
  src/index.ts
Labels: enhancement, semver:patch

#2217 docs: detail oauth configuration options and common cases
  docs/content/basic/authenticating-oauth.md
  docs/src/css/custom.css
  examples/oauth/app.js
Labels: docs

#2223 Bump `@slack/types` and consume event payloads from it
  package.json
  src/CustomFunction.ts
  src/WorkflowStep.ts
  src/middleware/builtin.spec.ts
  src/middleware/builtin.ts
  src/types/events/base-events.spec.ts
  src/types/events/base-events.ts
  src/types/events/index.ts
  src/types/events/message-events.spec.ts
  src/types/events/message-events.ts
Labels: semver:patch, TypeScript-specific, dependencies
