Repository slackapi/bolt-js, pull requests merged in 2024-12, with the labels that each got.

#2355 build: install @types/express@^v5 as a dev dependency for express@^5
  package.json
Labels: semver:patch, TypeScript-specific, dependencies

#2357 ci: check for linting errors without writing required changes
  package.json
Labels: tests, github_actions

#2363 build: find the biome config schema from the installed path
  biome.json
Labels: semver:patch

#2364 docs: show descriptions of function listener arguments
  docs/content/reference.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/reference.md
Labels: docs, semver:patch

#2362 build: ignore autogenerated docusaurus files when running the formatter
  biome.json
Labels: semver:patch

#2367 docs: replace redirected or missing links to bolt documentation
  README.md
  app.json
  docs/content/concepts/assistant.md
  docs/content/concepts/authenticating-oauth.md
  docs/content/deployments/aws-lambda.md
  docs/content/legacy/hubot-migration.md
  docs/content/reference.md
  docs/content/tutorials/ai-assistant.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/deployments/aws-lambda.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/reference.md
  examples/deploy-aws-lambda/README.md
  examples/deploy-heroku/README.md
  examples/getting-started-typescript/README.md
  package.json
  src/App.ts
  test/types/options.test-d.ts
Labels: docs, semver:patch

#2360 Upgrade dependencies
  package.json
Labels: semver:minor, dependencies

#2370 build: update the redirected repo homepage url to postfix js
  package.json
Labels: semver:patch

#2365 feat: make the app logger attached to the app instance public
  docs/content/concepts/assistant.md
  docs/content/concepts/custom-routes.md
  docs/content/concepts/deferring-initialization.md
  docs/content/concepts/error-handling.md
  docs/content/concepts/logging.md
  docs/content/concepts/receiver.md
  docs/content/concepts/socket-mode.md
  docs/content/getting-started.mdx
  docs/content/reference.md
  docs/content/tutorials/ai-assistant.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/custom-routes.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/deferring-initialization.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/error-handling.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/concepts/socket-mode.md
  docs/i18n/ja-jp/docusaurus-plugin-content-docs/current/getting-started.mdx
  src/App.ts
Labels: enhancement, docs, semver:minor, TypeScript-specific

#2371 chore(release): publish @slack/bolt@4.2.0
  package.json
Labels: semver:minor, release
