Repository slackapi/bolt-js, pull requests merged in 2024-04, with the labels that each got.

#2086 Update acknowledging_requests.md
  docs/_basic/acknowledging_requests.md
Labels: docs, semver:patch

#2098 Improve issue templates to ask for more relevant bolt information up front
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/question.md
Labels: docs

#2101 Publish 3.18.0
  package.json
Labels: semver:minor, release
