Repository slackapi/bolt-js, pull requests merged in 2025-05, with the labels that each got.

#2501 fix: allow all web api client option types in app initialization
  src/App.ts
  test/types/App.test-d.ts
Labels: bug, semver:patch, TypeScript-specific

#2517 fix: always attach the function inputs to the context if available
  src/App.ts
  test/unit/App/middlewares/arguments.spec.ts
Labels: bug, semver:patch

#2522 fix: bump sinon version
  package.json
  test/unit/App/basic.spec.ts
  test/unit/receivers/ExpressReceiver.spec.ts
  test/unit/receivers/HTTPReceiver.spec.ts
Labels: tests

#2519 fix: socket mode should warn when ack is invoked multiple times
  src/receivers/HTTPResponseAck.ts
  src/receivers/SocketModeReceiver.ts
  src/receivers/SocketModeResponseAck.ts
  src/types/receiver.ts
  test/unit/receivers/HTTPResponseAck.spec.ts
  test/unit/receivers/SocketModeReceiver.spec.ts
  test/unit/receivers/SocketModeResponseAck.spec.ts
Labels: enhancement, semver:minor, javascript

#2408 feat: support for synchronous custom step handling
  src/App.ts
  src/CustomFunction.ts
  src/middleware/builtin.ts
  src/types/events/index.ts
  test/types/function.test-d.ts
  test/unit/App/middlewares/global.spec.ts
  test/unit/App/routing-function.spec.ts
  test/unit/CustomFunction.spec.ts
  test/unit/helpers/events.ts
  test/unit/middleware/builtin.spec.ts
Labels: enhancement, semver:minor

#2538 chore: release @slack/bolt@4.4.0
  package.json
Labels: semver:minor, release

#2537 ci: pin actions workflow step hashes and use minimum permissions
  .github/workflows/ci-build.yml
  .github/workflows/docs-deploy.yml
  .github/workflows/samples.yml
  .github/workflows/triage-issues.yml
Labels: security, dependencies, github_actions

#2539 docs(fix): redirect links for project package migration guides to the tools site
  docs/content/migration/migration-v4.md
Labels: docs
