Repository slackapi/bolt-js, pull requests merged in 2025-09, with the labels that each got.

#2650 fix(typescript): accept empty list of suggested prompts for the assistant class
  src/Assistant.ts
  test/types/assistant.test-d.ts
Labels: bug, semver:patch, TypeScript-specific

#2632 fix: better ES module support for App class
  src/index.ts
Labels: enhancement, semver:patch, cla:signed

#2660 feat: accept assistant.threads.setStatus method arguments from the assistant class
  src/Assistant.ts
  test/unit/Assistant.spec.ts
Labels: bug, enhancement, semver:patch

#2661 docs: updates for combined quickstart
  docs/english/getting-started.md
Labels: docs
